[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "I"]
# F405: Star imports are useful for common project settings
ignore = ["F405"]

[tool.coverage.report]
fail_under = 80

[tool.mypy]
ignore_missing_imports = true
